spring:
  application:
    name: backend-funding
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    hikari:
      connection-test-query: select 1
      username: giveus
      password: giveus2024~!

server:
  port: 8083
#  address: localhost
  servlet:
#    context-path: /api/v1/funding
    encoding:
      charset: utf-8
      enabled: true
      force: true
management:
  health:
    refresh:
      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}

springdoc:
#  paths-to-match: /api/v1/funding
#  packages-to-scan: com.giveus.funding.controller
  swagger-ui:
    operations-sorter: alpha
    path: /docs
#  #    disable-swagger-default-url: true
  api-docs:
    path: /api/v1/funding/docs
