server:
  port: 8081

spring:
  application:
    name: backend-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth
            uri: lb://BACKEND-AUTH
            predicates:
              - Path=/auth/**
          - id: funding
            uri: lb://BACKEND-FUNDING
            predicates:
              - Path=/funding/**
  #        - id: payment
  #          uri: http://localhost:8084
  #          predicates:
  #            - Path=/payment/**
  #        - id: notify
  #          uri: http://localhost:8085
  #          predicates:
  #            - Path=/notify/**
