server:
  port: 8081

spring:
  application:
    name: backend-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      mvc:
        routes:
          - id: backend-auth
            uri: lb://BACKEND-AUTH
            predicates:
              - Path=/auth/**
          - id: backend-funding
            uri: lb://BACKEND-FUNDING
            predicates:
              - Path=/api/v1/funding/**
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
jwt:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa

springdoc:
  swagger-ui:
    path: /api/v1/docs
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api/v1/funding/docs
        name: Funding