eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: funding
          uri: http://localhost:8083
          predicates:
            - Path=/funding/**
        - id: payment
          uri: http://localhost:8084
          predicates:
            - Path=/payment/**
        - id: notify
          uri: http://localhost:8085
          predicates:
            - Path=/notify/**
