eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.34.127.65:8761/eureka

swagger:
  server: https://j10c206.p.ssafy.io

logging:
  file:
    path: /home/ubuntu/logs