server:
  port: 8081

spring:
  application:
    name: backend-gateway
  profiles:
    active: dev
#  main:
#    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credential
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true # JWT 나 쿠키를 사용해 메시지를 보내야 할 경우 true
            allowedHeaders: '*'
            allowedMethods: # 메서드를 명시하지 않으면 안되는 경우도 있기 때문에 메서드는 명시해주는 편이 좋다고 한다.
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: backend-auth
          uri: lb://BACKEND-AUTH
          predicates:
            - Path=/api/v1/auth/**
        - id: backend-funding
          uri: lb://BACKEND-FUNDING
          predicates:
            - Path=/api/v1/funding/**
        - id: backend-admin
          uri: lb://BACKEND-ADMIN
          predicates:
            - Path=/api/v1/admin/**
        - id: backend-payment
          uri: lb://BACKEND-PAYMENT
          predicates:
            - Path=/api/v1/payment/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
jwt:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa

springdoc:
  swagger-ui:
    path: /api/v1/docs
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api/v1/funding/docs
        name: Funding
      - url: /api/v1/admin/docs
        name: Admin
      - url: /api/v1/payment/docs
        name: Payment

