eureka:
  client:
    service-url:
      defaultZone: http://3.34.127.65:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://j10c206.p.ssafy.io:3306/prod?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true

swagger:
  server: https://j10c206.p.ssafy.io

coolsms:
  env:
    phone: '01071408821'
  api:
    key: NCSCISQV8JIPIKOV
    secret: PYZG3FBK0ETVDRT4N45O7DHFQ0CVTDGH
